server:
  port: 8081

spring:
  main:
    allow-circular-references: true

keycloak:
  realm: myrealm
  auth-server-url: http://localhost:8080/
  ssl-required: external
  resource: myclient
  credentials:
    secret: kBgiJWB3GIC92JAeCOTALS8m6NhjtRrT
  use-resource-role-mappings: true
  bearer-only: true
  cors: true